name: Testes Auth Service

on:
  push:
    branches: [ "test/unit-test-preparation" ]
    paths:
      - 'burguer-app/**'
  pull_request:
    branches: [ "test/unit-test-preparation" ]
    paths:
      - 'burguer-app/auth-service/**'

jobs:
  auth-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: burguer-app/auth-service

    steps:
    - name: ğŸ“¦ Checkout do cÃ³digo
      uses: actions/checkout@v4

    - name: ğŸ Configurar Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'

    - name: ğŸ“š Instalar dependÃªncias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: ğŸ§ª Rodar testes com cobertura
      run: |
        pytest --cov=. --cov-report=term-missing --cov-branch --cov-fail-under=80
