name: Docker Dev Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura o Docker Buildx (opcional, mas útil)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Instalação do docker-compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # Subir os containers do ambiente Dev
      - name: Bring up Docker Compose (Dev)
        run: |
          docker-compose down
          docker-compose up -d --build
        working-directory: ./burguer-app