name: Docker dev workflow

on:
  push:
    branches: [main]
   
  pull_request:
    branches: [main]

jobs:
  docker-up:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ“¦ Checkout do cÃ³digo
      uses: actions/checkout@v4

    - name: ðŸ³ Configurar Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "http://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Cria .env para todos os services
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> user-service/.env
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> auth-service/.env
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> order-service/.env
    
    - name: ðŸš€ Subir os containers
      run: | 
        docker-compose down
        docker-compose up -d --build
    
    - name: Waiting for services to be healthy
      run: |
        sleep 20  # Aguarda 20 segundos para garantir que os serviÃ§os estejam prontos
    
    - name: shut down containers
      working-directory: ./burguer-app
      run: |
        docker-compose down
